/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs631.bank.Group3;

import cs631.bank.Group3.Controller.TransactionTypeController;

public class App {

    public static void main(String[] args) {

        try(JdbcOracleConnection connection = JdbcOracleConnection.getInstance()){ 
            TransactionTypeController controller = new TransactionTypeController(connection.getDbConnection());
            controller.getTransactionType();
        } catch(Exception e){ 
            System.out.println(e);
        }
        

    }
}
