/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs631.bank.Group3;

import cs631.bank.Group3.Controller.TransactionTypeController;

public class App {

    public static void main(String[] args) {
        TransactionTypeController controller = new TransactionTypeController();
        controller.getTransactionType();
    }
}
