/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs631.bank.Group3;

import java.util.List;

class AppParent { 
    String getGreeting() {
        return "Hello from parent";
    }
}

public class App extends AppParent {
    
    @Override
    String getGreeting() {
        return "Hello World!";
    }

    public List<Integer> sort(List<Integer> str){ 
        str.sort( (s1, s2) -> {
            return s1 - s2;
        } );
        return str;
    }

    public static void main(String[] args) {
        AppParent parent = new App();
        System.out.println(parent.getGreeting());
    }
}
