/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs631.bank.pooja;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public List<Integer> sort(List<Integer> str){ 
        str.sort( (s1, s2) -> {
            return s1 - s2;
        } );
        return str;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
